### PR TITLE
Add more matchers 

### PR DESCRIPTION
**Pull request by flier**
- `anything` always matches, useful if you don't care what the object under test is
- `type_of` test type
- `all_of` matches if all matchers match, short circuits (like `&&`)
- `any_of` matches if any matchers match, short circuits (like `||`)

### CODE REVIEW

**Comment by povilasb** [comment]
Cool, it seems like `rustfmt` fails. If you got that fixed, maybe this PR could be merged?

**Comment by povilasb** [comment]
nice!

@carllerche what do you say, can we get this merged? :)

**Comment by carllerche** [comment]
I would ping @ujh as they are maintaining this repo :) I should probably transfer it out of my github at this point.

**Comment by ujh** [comment]
Sorry for the delay! I will look into this in the next days, thanks for the work.

@carllerche: Let me know what the best way would be to transfer this.

**Comment by ujh** [comment]
So things I noticed @flier:

1. Don't forget to add yourself as an author in the `Cargo.toml` file
1. Could you have a look at the copyright notices again? If they're new files and it's code you wrote just add yourself there. Or are they existing files that you moved around?
1. Documentation! It would be great to let everyone know about the additional features you added. It doesn't have to be much, just a few examples in the README.

**Comment by flier** [comment]
@ujh Thanks, please review the changes

**Comment by povilasb** [comment]
`rustfmt` is failing: https://travis-ci.org/ujh/hamcrest-rust/jobs/299441032 :/

**Comment by ujh** [comment]
Very cool. Thank you!

**Pull request merged**
